tinygo-org/tinygo-site

content/microcontrollers/_index.md, content/microcontrollers/arduino-uno.md, content/microcontrollers/bbc-microbit.md, content/microcontrollers/bluepill.md, content/microcontrollers/digispark.md, content/microcontrollers/itsybitsy-m0.md, content/microcontrollers/nrf52840-mdk.md, content/microcontrollers/pca10031.md, content/microcontrollers/pca10040.md, content/microcontrollers/pca10056.md, content/microcontrollers/reelboard.md
This PR adds flashing instructions for all currently supported boards.
=> boards: add flashing instructions for all currently supported boards

content/compiler-internals/datatypes.md
This is here to adjust after this PR, and should only be merged after that PR is merged: https://github.com/tinygo-org/tinygo/pull/178
=> datatypes: update complex number datatypes

content/compiler-internals/datatypes.md, content/lang-support/_index.md
Little has really changed.
fixes #14
=> compiler-internals: update status to v0.5.0

content/usage/basic.md, content/webassembly/webassembly.md
Add more details about building and running WebAssembly in the browser.
=> content: add more WebAssembly information

content/getting-started/using-docker.md, content/usage/basic.md, content/webassembly/webassembly.md
=> Docker instructions improvements

content/getting-started/linux.md
=> getting-started: add arch linux instructions

content/lang-support/stdlib.md, imports/Makefile, imports/main.go
Based on the work by @trashhalo:
https://github.com/trashhalo/tinygo-import-report
=> lang-support: add list of packages that can be imported

content/getting-started/linux.md
Much easier for users to install.
=> Add Arch Linux package link

content/microcontrollers/bbc-microbit.md
Update info for users on MacOS
=> Update bbc-microbit with info MacOS

content/usage/basic.md
Bring description of micro:bit example in line with how the code actually works.
=> usage: update micro:bit description

content/microcontrollers/nucleo-f103rb.md
See https://github.com/tinygo-org/tinygo/pull/565 for the corresponding code changes.
=> boards: add NUCLEO-F103RB to list of supported boards

content/lang-support/stdlib.md, imports/main.go
Also, limit the max number of lines to 15 for excessively long outputs.
=> lang-support: update list of importable packages

content/getting-started/macos.md, content/usage/basic.md
These are some suggestions to some macOS-related documents, that I found it could be better if updated.
=> Update some macOS related instructions

content/faq/why-go-instead-of-rust.md
Just wanted to update the link to my homepage, which has recently been moved.
=> Update link to homepage

content/microcontrollers/pinetime.md
See also https://github.com/tinygo-org/tinygo/pull/661
=> boards: add PineTime description

content/usage/subcommands.md
See https://github.com/tinygo-org/tinygo/pull/666
=> usage: update gdb subcommand documentation

content/lang-support/_index.md
=> lang-support: update to match the TinyGo 0.10 release

content/microcontrollers/_index.md, content/microcontrollers/pybadge.md
Add support for Adafruit PyBadge, thanks to @conejoninja for adding support.
=> boards: add support for Adafruit PyBadge

content/webassembly/webassembly.md
=> Add Return Value to "func add()"

content/getting-started/windows.md
just fixed a typo.
many sure -> make sure
=> Fix typo in getting started windows.md
