tinygo-org/tinygo-site

- static/x/go-llvm/index.html
go-llvm has moved, add a redirect for vanity imports.
> static: add redirect for go-llvm

- content/compiler-internals/heap-allocation.md
- content/lang-support/_index.md
Add a page that describes which part of Go is supported and which is not. Most features require some explanation as they are only partially supported.
Also, some updates to the "heap allocation" page.
When this is live, I would like to replace the part in the README with a link to this page.
> Language support in docs

- content/microcontrollers/bbc-microbit.md
Rather than install `OpenOCD`, Micro:bit devices mount as USB devices ([DAPLink](https://github.com/ARMmbed/DAPLink))when connected to a host and it is possible to flash software to them using a simply copy command.
This *may* apply to other supported devices too and provides an easier path to flashing.
> Augment OpenOCD requirement with file copy

- content/microcontrollers/drivers/_index.md
This PR adds a page with links to TinyGo drivers repo and list of supported drivers.
> drivers: add page with links to TinyGo drivers repo, and list of drivers

- content/getting-started/_index.md
- content/getting-started/linux.md
- content/getting-started/macos.md
Installing TinyGo using system libraries and by installing LLVM from
source is done very differently. Add information about using system
libraries and make the distinction clear.
This should avoid confusion like in https://github.com/tinygo-org/tinygo/issues/297.
Please note that I haven't managed to get Hugo to work, it somehow ignores the new page I've added. So it should be checked before merging this PR.
> getting-started: clarify and extend "install from source" instructions

- content/compiler-internals/volatile.md
- content/lang-support/_index.md
- content/usage/important-options.md
There were a few changes that affect the docs, in particular in language support.
I'm not sure in which branch this is supposed to be merged.
> all: update to TinyGo 0.6

- content/getting-started/_index.md
> Add platform specific installation links in getting started page

- content/microcontrollers/_index.md
- content/microcontrollers/arduino-nano33-iot.md
Adds information about using TinyGo on the Arduino Nano33 IoT board.
> boards: add info about support for the Arduino Nano33 IoT board

- content/getting-started/linux.md
Releases for 0.7.1 do not include any packages for armf. This PR addresses that.
> Update doc to reflect lack of armhf deb file

- content/microcontrollers/arduino-uno.md
It's a bit of duplication (especially the `avrdude` part, which is mentioned twice on this page) but it may help people new to TinyGo.
I wasn't sure whether to include these error messages, they take up quite a bit of space but may be helpful to quickly diagnose the problem.
See https://github.com/tinygo-org/tinygo/issues/504
> boards: add installation instructions for Arduino Uno

- content/compiler-internals/datatypes.md
- content/compiler-internals/differences-from-go.md
- content/compiler-internals/heap-allocation.md
- content/compiler-internals/microcontrollers.md
- content/lang-support/_index.md
Lots of things have changed, so I went through most compiler docs and
updated them. For example, one page said there was no GC support yet,
that's fixed now.
Fixes #41.
> all: update to newer TinyGo version

- content/getting-started/linux.md
- content/getting-started/macos.md
This PR adds info for Go modules based source install which is the current set of source requirements since the 0.8.0 release.
It corrects issue #45
> docs: add info for Go modules based source install

- content/microcontrollers/pca10031.md
- content/microcontrollers/pca10040.md
- content/microcontrollers/pca10056.md
I followed the link and it returned a 404, found the new URL in their docs
> update link to correct zephyrproject URL in pca100xx files

- content/usage/basic.md
On a just-bought board, the instructions didn’t work because boards are shipped in MakeCode mode, which requires just one RESET press.
> basic: clarify Circuit Playground Express

- content/compiler-internals/calling-convention.md
- content/compiler-internals/datatypes.md
- content/compiler-internals/differences-from-go.md
- content/compiler-internals/harvard-arch.md
- content/compiler-internals/heap-allocation.md
- content/compiler-internals/interrupts.md
- content/compiler-internals/microcontrollers.md
- content/compiler-internals/pipeline.md
- content/faq/why-a-new-compiler.md
See: https://github.com/tinygo-org/tinygo/pull/782
Also reorder other pages a bit, in order from "relevant if you're doing low-level stuff as a user" to "if you want to dig deeper into the compiler".
> compiler-internals: add page on interrupts

- content/getting-started/linux.md
When installing Go out of the box, setting a GOPATH isn't necessary any more, but the internal one is still being used for go get, which is in $HOME/go. To access GOPATH also when it is not set in the shell you use, use go env GOPATH instead of $GOPATH.
> Making GOPATH command work on newer systems

- content/faq/what-about-esp8266-esp32.md
both the Clang fork and the LLVM fork archived. I updated the link to the LLVM fork.
> update link to Espressif llvm project

- content/ide-integration/_index.md
Started an IDE Integration section.
> Started IDE Integration section

- content/microcontrollers/arduino-nano33-iot.md
Regard to https://github.com/tinygo-org/tinygo-site/issues/78.
I just added couple line for bossac installation in debian/ubuntu based system since it has some dependencies of wxgtk and readline libraries. 
But I am not sure if the originally guide was intentionally written in that simpler way for readability.
If so, please let me know and dismiss.
> Update arduino-nano33-iot for bossa install

- content/microcontrollers/machine/particle-argon.md
- content/microcontrollers/machine/particle-boron.md
- content/microcontrollers/machine/particle-xenon.md
- content/microcontrollers/particle-argon.md
- content/microcontrollers/particle-boron.md
- content/microcontrollers/particle-xenon.md
- doc-gen/Makefile
This PR adds Particle Argon, Boron and Xenon boards to the docs.
It's blocked by https://github.com/tinygo-org/tinygo/pull/904 after which is merged, we can run `make doc-gen` to generate `machine` package docs for those boards.
> [WIP] Add Particle Argon, Boron and Xenon

- content/getting-started/linux.md
- content/getting-started/macos.md
The biggest change is that `GO111MODULE` isn't necessary anymore with a go.mod file in the root directory.
> getting-started: fix the docs for recent Go, LLVM and Debian versions
